version: "3"

services:
  ros:
    image: ros_noetic:latest
    container_name: final
    privileged: true
    environment:
      - DISPLAY=trg-A4000:10
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=burger
      #- WAYLAND_DISPLAY
      #- XDG_RUNTIME_DIR
      - PULSE_SERVER
      #- LIBGL_ALWAYS_INDIRECT=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /home/miki/docker:/root/catkin_ws/src
    tty: true
    command: zsh -c "source /root/catkin_ws/devel/setup.zsh"
    network_mode: "host"
    extra_hosts:
      - "host:127.0.0.1" # Seems that this might be needed for ROS networking
      - "host:192.168.0.2" # The host PC
      - "ur:192.168.0.3" # UR IP
    expose:
      - "50001" # send commnad to UR
      - "50002" # external control of UR
      - "50003" # recerve commnad from UR
      - "50004" # script_command_port of UR
